name: desafio_login
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/alucard.jpg
    - assets/umbrella-logo.jpg
    - assets/leon-avatar.jpg
  fonts:
      - family: Nunito
        fonts:
          - asset: assets/Nunito.ttf


